export const data = [
  [
    ["From", "To", "Weight"],
    ["Vanderbilt 2020 Emissions", "Scope 1 Emissions", 70860],
    ["Vanderbilt 2020 Emissions", "Scope 2 Emissions", 39661],
    ["Vanderbilt 2020 Emissions", "Scope 3 Emissions", 47841],
    ["Scope 1 Emissions", "Natural Gas", 69078],
    ["Scope 1 Emissions", "Other Energy Sources", 1782],
    ["Scope 2 Emissions", "Purchased Electricity", 39661],
    ["Scope 3 Emissions", "Waste Disposal and Recycling", 2394],
    ["Scope 3 Emissions", "Air Travel", 9919],
    ["Scope 3 Emissions", "Commuting", 35528],
  ],
  [
    ["From", "To", "Weight"],
    ["Vanderbilt 2021 Emissions", "Scope 1 Emissions", 70428],
    ["Vanderbilt 2021 Emissions", "Scope 2 Emissions", 27092],
    ["Vanderbilt 2021 Emissions", "Scope 3 Emissions", 23733],
    ["Scope 1 Emissions", "Natural Gas", 69114],
    ["Scope 1 Emissions", "Other Energy Sources", 1314],
    ["Scope 2 Emissions", "Purchased Electricity", 27092],
    ["Scope 3 Emissions", "Waste Disposal and Recycling", 3273],
    ["Scope 3 Emissions", "Air Travel", 485],
    ["Scope 3 Emissions", "Commuting", 20613],
  ],
  [
    ["From", "To", "Weight"],
    ["Vanderbilt 2022 Emissions", "Scope 1 Emissions", 69463],
    ["Vanderbilt 2022 Emissions", "Scope 2 Emissions", 34297],
    ["Vanderbilt 2022 Emissions", "Scope 3 Emissions", 24298],
    ["Scope 1 Emissions", "Natural Gas", 67870],
    ["Scope 1 Emissions", "Other Energy Sources", 1592],
    ["Scope 2 Emissions", "Purchased Electricity", 34297],
    ["Scope 3 Emissions", "Waste Disposal and Recycling", 2561],
    ["Scope 3 Emissions", "Air Travel", 6402],
    ["Scope 3 Emissions", "Commuting", 15335],
  ],
  [
    ["From", "To", "Weight"],
    ["Vanderbilt 2023 Emissions", "Scope 1 Emissions", 63021],
    ["Vanderbilt 2023 Emissions", "Scope 2 Emissions", 35855],
    ["Vanderbilt 2023 Emissions", "Scope 3 Emissions", 14947],
    ["Scope 1 Emissions", "Natural Gas", 61958],
    ["Scope 1 Emissions", "Other Energy Sources", 1063],
    ["Scope 2 Emissions", "Purchased Electricity", 35855],
    ["Scope 3 Emissions", "Waste Disposal and Recycling", 2551],
    ["Scope 3 Emissions", "Air Travel", 6942],
    ["Scope 3 Emissions", "Commuting", 5453],
    ["Natural Gas", "Offset by Clearloop", 61958],
    ["Other Energy Sources", "Offset by Clearloop", 1063],
    ["Purchased Electricity", "Offset by Silicon Ranch", 35855],
    ["Waste Disposal and Recycling", "Offset by Clearloop", 2551],
    ["Air Travel", "Offset by Clearloop", 6942],
    ["Commuting", "Offset by Clearloop", 5453],
  ],
];

export const descriptions = [
  "Scope 1 emissions are direct emissions from sources that are controlled by Vanderbilt. The most significant source of Scope 1 emissions at Vanderbilt is natural gas use at the on-campus power plant and in individual buildings. Additional Scope 1 emissions include fleet vehicles, diesel use at the power plant, emergency generators, anesthetic gas use and refrigerant releases.",
  "Scope 2 emissions are indirect emissions from purchased electricity. Vanderbilt's Scope 2 emissions are entirely from electricity purchased from Nashville Electric Service.",
  "Scope 3 emissions are emissions that are not directly controlled by Vanderbilt but are associated with Vanderbilt. Scope 3 emissions at Vanderbilt include faculty, staff, postdoc and graduate/professional student commuting, air travel, waste disposal and recycling.",
  "Almost all of Vanderbilt's Scope 1 emissions are from the on-campus power plant.",
  "Additional Scope 1 emissions come from various sources, but are relatively small in comparison to the emissions from the power plant. Scope 1 emissions make up over 55% of total emissions.",
  "All of Vanderbilt's Scope 2 emissions come from NES, who purchases their energy from the TVA. As of 2023, this energy's sources are 39.8% nuclear, 25.8% coal-fired, 21.5% natural gas-fired, 9.7% hydroelectric power, and 3.2% from wind and solar.",
  "Of Vanderbilt’s Scope 3 emissions, waste and recycling is responsible for 2 percent of the total GHGs that Vanderbilt emitted as of 2023. To combat this, Vanderbilt will stop most institutional single-use plastic purchases by 2025, and expand food waste collection to include all dining areas and residential halls.",
  "Vanderbilt offsets the carbon emissions created from air travel from faculty, staff, postdoc and graduate students.",
  "Vanderbilt offsets the carbon emissions created from commuting to campus from faculty, staff, postdoc and graduate students.",
  "Clearloop has partnered with Vanderbilt to offset the university's scope 1 emissions.",
  "Clearloop has partnered with Vanderbilt to offset the university's scope 1 emissions.",
  "Silicon Ranch has partnered with Vanderbilt to offset the university's scope 2 emissions.",
  "Clearloop has partnered with Vanderbilt to offset the university's scope 3 emissions.",
  "Clearloop has partnered with Vanderbilt to offset the university's scope 3 emissions.",
  "Clearloop has partnered with Vanderbilt to offset the university's scope 3 emissions.",
];
